default: &default
  adapter: postgresql
  pool: 5
  user: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: test_dev

test:
  <<: *default
  database: test_test



production:
  <<: *default
  database: test_prod
